### PR TITLE
Change docker port to 9000 for testing

### PR DESCRIPTION
**Pull request by MikeMcC399**
- This PR resolves issue https://github.com/corona-warn-app/cwa-map-public-frontend/issues/24 by amending the README documentation (see confirmation in https://github.com/corona-warn-app/cwa-map-public-frontend/issues/24#issuecomment-1237386440).

### CODE REVIEW

**Review by GisoSchroederSAP — APPROVED** [review]
As we expect no side-effects, this minor adjustment is fine.

**Comment by MikeMcC399** [comment]
Apologies. The incorrect port number was listed in two places and previously I had only corrected one instance. I've now corrected both occurrences in the README.

**Comment by MikeMcC399** [comment]
@GisoSchroederSAP 

Thank you for your approval. Will you merge this PR now?

**Comment by MikeMcC399** [comment]
@dreske 

Perhaps you could merge this correction to the README?

**Comment by MikeMcC399** [comment]
Still waiting for merge of this approved documentation error correction.

**Pull request merged**
