### PR TITLE
fix link in logo

### LINKED ISSUE #4: Link on logo refers to sharp
## Avoid duplicates
* [x]  Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x]  Bug is not already reported in another issue

## Technical details
* Device: Windows 10
* Browser: Microsoft Edge 97.0.1072.55 

## Describe the bug
The link on the cwa-logo in the header of the static pages points to # instead of root page.

## Steps to reproduce the issue
1. Browse to https://map.schnelltestportal.de/
2. Click on cwa logo

## Expected behaviour
The link on the logo should point to the root page ("/") as the link on the title does

## Possible Fix
Change # to /
If codeowner agrees pull request can be created
marc-ah/cwa-map-public-frontend

## Additional context
-/-

### PR DESCRIPTION
**Pull request by marc-ah**
Fixes #4

### CODE REVIEW

**Comment by dreske** [comment]
Pull request is still draft, so can't be merged.

**Comment by dreske** [comment]
Sorry, in the meantime we have renamed one file, so the conflict must be solved in die PR :D

**Comment by marc-ah** [comment]
> Sorry, in the meantime we have renamed one file, so the conflict must be solved in die PR :D

that figures :D

**Comment by MikeMcC399** [comment]
@dreske 
How will this change be deployed to the production site?

I can't see anything changed on https://map.schnelltestportal.de/ so far.

**Pull request merged**
